const Employee=[
    {
        id:'102',
        empName:'jhon',
        age:'25',
        designation:'Developer',
        salary:'35000'
    },
    {
        id:'103',
        empName:'Anu',
        age:'25',
        designation:'Tester',
        salary:'35000'
    },
     {
        id:'104',
        empName:'Neethu',
        age:'25',
        designation:'HR',
        salary:'35000'
    },
    {
        id:'105',
        empName:'Neeraj',
        age:'25',
        designation:'Developer',
        salary:'35000'
    },
    {
        id:'106',
        empName:'Sanjay',
        age:'25',
        designation:'Developer',
        salary:'35000'
    },
    {
        id:'107',
        empName:'Ajay',
        age:'25',
        designation:'Developer',
        salary:'35000'
    },
]
export default Employee;